# MikroTik CHR configuration - ${hostname}
# Generated by Terraform - apply via RouterOS terminal or MikroTik API after first boot

# Basic identity
/system identity set name=${hostname}

# WAN interface (DHCP)
/ip dhcp-client add interface=ether1 disabled=no add-default-route=yes

# LAN interface
/ip address add address=${lan_ip}/${lan_cidr} interface=ether2

# VRRP
/interface vrrp add name=vrrp1 interface=ether2 vrid=1 priority=${vrrp_priority} interval=1s
/ip address add address=${vrrp_vip}/16 interface=vrrp1

# NAT - masquerade LAN traffic going out WAN
/ip firewall nat add chain=srcnat out-interface=ether1 action=masquerade

# DNS forwarding
/ip dns set allow-remote-requests=yes servers=${dns_servers}

# Firewall - basic protection
/ip firewall filter
add chain=input action=accept connection-state=established,related
add chain=input action=accept protocol=icmp
add chain=input action=accept src-address=172.16.0.0/16
add chain=input action=accept protocol=tcp dst-port=8291 comment="Allow Winbox"
add chain=input action=accept protocol=udp dst-port=112 comment="VRRP"
add chain=input action=drop

add chain=forward action=accept connection-state=established,related
add chain=forward action=accept src-address=172.16.0.0/16
add chain=forward action=drop connection-state=invalid
add chain=forward action=drop

# K8s API Load Balancer (DST-NAT)
/ip firewall nat add chain=dstnat dst-port=${k8s_api_port} protocol=tcp action=dst-nat to-addresses=${k8s_cp_1} to-ports=${k8s_api_port} per-connection-classifier=both-addresses:3/0
/ip firewall nat add chain=dstnat dst-port=${k8s_api_port} protocol=tcp action=dst-nat to-addresses=${k8s_cp_2} to-ports=${k8s_api_port} per-connection-classifier=both-addresses:3/1
/ip firewall nat add chain=dstnat dst-port=${k8s_api_port} protocol=tcp action=dst-nat to-addresses=${k8s_cp_3} to-ports=${k8s_api_port} per-connection-classifier=both-addresses:3/2
